[package]
name = "example-http-hello-world"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
axum = "0.8.3"
caslex = { path = "../../caslex" }
tokio = { version = "1.44.2", features = ["full"] }
utoipa = "5.3.1"
utoipa-axum = "0.2.0"

[lints]
workspace = true
