name: CI

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@beta
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: Check
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      - name: rustfmt
        run: cargo fmt --all --check

  check-docs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: cargo doc -p axum-core
        run: cargo doc --package axum-core --all-features --no-deps
      - name: cargo doc -p axum
        run: cargo doc --package axum --all-features --no-deps
      - name: cargo doc -p axum-extra
        run: cargo doc --package axum-extra --all-features --no-deps
    env:
      RUSTDOCFLAGS: "-D rustdoc::all -A rustdoc::private-doc-tests"